### PR TITLE
fix: set yuv full range flag to 1 for VP9 with sRGB

### LINKED ISSUE #990: Incorrect implementation of color_range in VP9?
I was looking through the specs of VP9 (https://storage.googleapis.com/downloads.webmproject.org/docs/vp9/vp9-bitstream-specification-v0.6-20160331-draft.pdf) and the implementation of VP9 parser in shaka-packager. I think I found a bug in the parsing of color_range.

In particular, if color_space is VPX_COLOR_SPACE_SRGB, the specs says that color_range should be 1 i.e. yuv_full_range = true. However, yuv_full_range is default initialized as false and isn't set in the branch for color_space is VPX_COLOR_SPACE_SRGB.

### PR DESCRIPTION
**Pull request by cosmin**
If color_space is VPX_COLOR_SPACE_SRGB, the specs says that color_range should be 1 i.e. yuv_full_range = true. However, yuv_full_range is default initialized as false and isn't set in the branch for color_space is VPX_COLOR_SPACE_SRGB.

Fixes #990

### CODE REVIEW

**Review by joeyparrish — APPROVED** [review]

File: packager/media/codecs/vp9_parser.cc [hunk 1]
```diff
@@ -285,6 +285,7 @@ bool ReadBitDepthAndColorSpace(BitReader* reader,
     }
   } else {
     // Assume 4:4:4 for colorspace SRGB.
+    yuv_full_range = 1;
```
Comment (joeyparrish) [inline packager/media/codecs/vp9_parser.cc:288]: nit: it's a bool, so `yuv_full_range = true`

**Review by joeyparrish — CHANGES_REQUESTED** [review]

File: packager/media/codecs/vp9_parser.cc (hunk 1 above)
Comment (joeyparrish) [reply packager/media/codecs/vp9_parser.cc]: Done

**Review by joeyparrish — APPROVED** [review]
